### PR TITLE
add: login signup

### PR DESCRIPTION
**Pull request by Sudhanshusoni45**
Login:[Link to Preview](https://0g8sfb.csb.app/login)
Signup:[Link to Preview](https://0g8sfb.csb.app/signup)

### CODE REVIEW

**Review by AtulPant2704 — COMMENTED** [review]
You can just add a navbar to them and have a respective page for each of them so that you can navigate to other pages and in ProductListing page, you have login button you can add Link to that button and then it can route to login page. And in Login page, you can add link to bottom of the form to Create New Account and that page would take user to SignUp page.

Or you can load your Login and SignUp as modal as well.

**Review by kart-c — APPROVED** [review]

**Comment by kart-c** [comment]
Sudhanshu are you going to make these components as a modal? If so then its good. If not then you need to provide some way for the user to navigate to some other page, in case the user does not want to login or signup

**Comment by Sudhanshusoni45** [comment]
Thank you @kart-c @AtulPant2704 i have added Navbar to login/signup page.

**Review by AtulPant2704 — APPROVED** [review]
You can add links to elements present in Navbar, rest all looks good. And I would advise you to have a link at bottom of login form to take that user to signup page if he does not have the account, rest all looks good.

**Pull request merged**
